const similarDepartments: Record<string, string[]> = {
  ACC: ['BUS', 'ECO', 'FIN'],
  BUS: ['ACC', 'ECO', 'FIN', 'MGT', 'MKT'],
  ECO: ['BUS', 'ACC', 'FIN'],
  FIN: ['BUS', 'ACC', 'ECO'],
  MGT: ['BUS', 'ACC'],
  MKT: ['BUS', 'ACC'],
  COS: ['MAT', 'STA', 'ENG'],
  MAT: ['COS', 'STA', 'PHY'],
  STA: ['MAT', 'COS', 'ECO'],
  BIO: ['CHE', 'PHY'],
  CHE: ['BIO', 'PHY'],
  PHY: ['MAT', 'CHE', 'BIO'],
  ENG: ['COM', 'HIS'],
  HIS: ['POL', 'ENG'],
  POL: ['HIS', 'ECO'],
}

export const schedulingConfig = {
  maxHistoryRuns: 24,
  maxHistoryPerCourse: 32,
  maxHistoryForProfile: 120,
  historyRecencyDecay: 0.85,
  guardedRoomDisplayNamesRequiringRealData: [] as string[],
  similarity: {
    enrollmentDeltaAbsolute: 10,
    enrollmentDeltaPercent: 0.25,
  },
  abnormalPlacement: {
    penaltyScore: 800,
    requireHistoricalBuilding: true,
  },
  weights: {
    currentPreferredDays: 45,
    currentPreferredTimes: 45,
    currentAvoidTimes: -60,
    currentPreferredRoom: 40,
    currentPreferredBuilding: 30,
    officeBuilding: 10,
    capacityFit: 8,
    backToBack: 10,
    historyExactPlacement: 55,
    historyExactTime: 28,
    historyExactRoom: 20,
    historyBuilding: 12,
    historyFloor: 8,
    historyRoomType: 8,
    historyCapacityBand: 6,
    historicalPreferenceDays: 8,
    historicalPreferenceTimes: 8,
    professorHistory: 22,
    similarProfessorHistory: 14,
    similarCourseHistory: 20,
    departmentHistory: 12,
    similarDepartmentHistory: 10,
  },
  similarDepartments,
} as const
